### ISSUE TITLE
Upcoming changes to the wifi dongle

### ISSUE THREAD

**Issue by diagonalciso** [ayasystems/SolaxHTTP#2]
Is anyone still working on this? 
The firmware on the dongle will get a upgrade, after which this repo won't work anymore.

Contact me, if you like.

**Comment by ayasystems** [comment]
You have an email.

**Comment by ghost** [comment]
All I got was a notification email. Look me up on Twitter for DM if you like.

**Comment by diggahpl** [comment]
Great project! Is there any way to support X3 inverter to see s1,s2,s3 parameters ?

**Comment by MartinT72** [comment]
Hello Ayasystems,

I tried the plugin but is is not able to extract the data from the Solax
Firmware version of the dongle is 2.033.20

The script is running but get no data 

13:59:10.479 (Solax) onHeartbeat called, run again in 1 heartbeats.
13:59:11.482 (Solax) self.runAgain | self.httpConn -> Name: 'HTTP Test', Transport: 'TCP/IP', Protocol: 'HTTP', Address: '10.10.10.11', Port: '80', Baud: -1, Connected: False, Parent: 'None'
13:59:11.482 (Solax) Transport set to: 'TCP/IP', 10.10.10.11:80.
13:59:11.482 (Solax) Connect directive received, action initiated successfully.
13:59:11.533 (Solax) Solax connected successfully.
13:59:11.533 (Solax) Sending 205 bytes of data
13:59:12.248 (Solax) Queued asynchronous read aborted (10.10.10.11:80), [2] End of file.
13:59:12.285 (Solax) Disconnect event received for '10.10.10.11:80'.
13:59:12.285 (Solax) onDisconnect called for connection to: 10.10.10.11:80
13:59:12.486 (Solax) onHeartbeat called, run again in 1 heartbeats.

Any help with this?

**Comment by ghost** [comment]
You have the latest version of the Solax firmware in which they made some changes, breaking the script. You can try to downgrade the firmware, but I'd advice against it because their where some privacy issues in it. 

They added authentication in the newest firmware that didn't exist in the old firmware. They also added encryption, but I don't have the full details about it. 

The script has to be revised to be able to work with the latest firmware.

**Comment by MartinT72** [comment]
That's unfortunately
Any good suggestions to pull the info from the Solax Cloud?
I've tried some but none of them seems to work properly getting all the data this plugin is able to get

**Comment by ghost** [comment]
No, I don't know a better option since I never tested their cloud.
Of what I know about Solax and the way they dealt with the issues in the old firmware I would stay away from their cloud entirely.

But that's just my personal opinion.
Also, I will never buy anything from them again.

**Comment by MartinT72** [comment]
Is somebody working on updating the script?
The encryption is interesting - it does not seem to be HTTPS (to only open port is port 80)
Adding a username and password is not that difficult I assume

**Comment by ayasystems** [comment]
Hi MartinT72

I did this plugin without solax. I haven't a FV installation so I need info to build a compatible version with the new firmware....
