### ISSUE TITLE
Support for X3 invertetr

### ISSUE THREAD

**Issue by diggahpl** [ayasystems/SolaxHTTP#3]
Great project! 

Any chance to support X3 model to see all data ? 
{"type":"X3-MIC","SN":"SWSDXXXXXF","ver":"2.033.20","Data":[1.0,1.2,330.5,346.1,1.1,229.9,673,32,2.1,24.1,0,319,397,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0.00,213,227,233,1.2,1.2,230.3,229.5,50.02,50.03,50.02,0,0,0,0,0,0,0,0.00,0,8,0,0,0.00,0,8,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"Information":[5.000,7,"X3-MIC","MC502TG6XXXXX",1,1.21,1.02,1.25,1.02]}

**Comment by ayasystems** [comment]
Whats the meaning of each field? Do you know?
